name: "Coverage"

on:
  push:
    branches: [main]
  pull_request: {}
jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    env:
      PYTHONPATH: src
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Quicktype
        run: npm install -g quicktype
      - name: Install dependencies
        run: uv sync --group coverage
      - name: Run Tests and Record Coverage
        run: |
          uv run coverage run -m pytest
          uv run coverage html --omit "unittests/*"
          uv run coverage report --fail-under 70 --omit "unittests/*"
