name: "Unittests"

on:
  push:
    branches: [main]
  pull_request: {}
jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    env:
      PYTHONPATH: src
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '22'
      - name: Install Quicktype
        run: npm install -g quicktype
      - name: Install Dependencies
        run: uv sync --group tests
      - name: Run the Unit Tests
        run: uv run python -m pytest
